services:
  postgres:
    image: postgres:16-alpine
    container_name: postgre-chrisapi
    labels:
      project: "christ-api"
      service: "database"
    env_file:
      - .env.docker
    ports:
      # Internal port pada container, external port di host
      # Ganti 5433 jika sudah dipakai
      - "5433:5432"
    volumes:
      - christ_postgres_data:/var/lib/postgresql/data
      - ./docs/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U christ_user"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - christ-network
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang-christapi
    labels:
      project: "christ-api"
      service: "api"
    env_file:
      - .env.docker
    ports:
      # Ganti 3001 jika port 3000 sudah dipakai
      - "3001:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - christ-network
    restart: unless-stopped

  migrate:
    image: migrate/migrate
    container_name: migrate_christapi
    env_file:
      - .env.docker
    volumes:
      - ./migrations:/migrations
    networks:
      - christ-network
    entrypoint: ["migrate"]
    depends_on:
      - postgres
    restart: "no"

volumes:
  christ_postgres_data:

networks:
  christ-network:
    driver: bridge
    name: christ-network
